version: "3.8"

services:
  frontend:
    user: root
    build: .
    command: npm run dev
    volumes:
      - .:/app:z
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_TASK_SERVICE_URL=/api/tasks
      - NEXT_PUBLIC_PROJECT_PROFESSIONAL_SERVICE_URL=/api/professional
      - NEXT_PUBLIC_KEYCLOAK_URL=/keycloak 
      - NEXT_PUBLIC_KEYCLOAK_REALM=master
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=frontend-app

    networks:
      - app-network

networks:
  app-network:
    external: true
